[#ftl]
[@addResourceGroupInformation
    type=NETWORK_ROUTER_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_TRANSIT_GATEWAY_SERVICE
        ]
/]
