[#ftl]
[@addResourceGroupInformation
    type=FILETRANSFER_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_TRANSFER_SERVICE
        ]
/]
