[#ftl]
[@addResourceGroupInformation
    type=LB_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_ELASTIC_LOAD_BALANCER_SERVICE,
            AWS_WEB_APPLICATION_FIREWALL_SERVICE,
            AWS_KINESIS_SERVICE,
            AWS_CLOUDWATCH_SERVICE,
            AWS_IDENTITY_SERVICE
        ]
/]

[@addResourceGroupInformation
    type=LB_PORT_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_ELASTIC_LOAD_BALANCER_SERVICE,
            AWS_VIRTUAL_PRIVATE_CLOUD_SERVICE,
            AWS_ROUTE53_SERVICE,
            AWS_CERTIFICATE_MANAGER_SERVICE
        ]
/]
