[#ftl]
[@addResourceGroupInformation
    type=GLOBALDB_COMPONENT_TYPE
    attributes=[]
    provider=AWS_PROVIDER
    resourceGroup=DEFAULT_RESOURCE_GROUP
    services=
        [
            AWS_DYNAMODB_SERVICE
        ]
/]
